In [5]:
import numpy as np
from cs231n.layer_utils import *

# Weight initialisation
Test on how to initialise all network weights.

In [40]:
N = 8
num_classes=3
hidden_dims = [10, 5]
input_dim = 2*2
weight_scale = 1
params = {}
X = np.random.randn(N, input_dim)
network_size = len(hidden_dims)

params = {}
dims = [input_dim] + hidden_dims + [num_classes]
network_size = len(dims)
for layer_index in range(1, network_size):
    l_size = dims[layer_index]
    l_size_prev = dims[layer_index-1]
    params["W"+str(layer_index)] = weight_scale * np.random.randn(l_size_prev, l_size)
    params["b"+str(layer_index)] = np.zeros(l_size)
[l.shape for l in params.values()]

[(4, 10), (10,), (10, 5), (5,), (5, 3), (3,)]

## Why the gradient update may all positive or all negative. 

With a sigmoid activation function we have the problem that when the input vector to a sigmoid node is all positive the weight updates will also be all positive. In other words the sign of the gradient vector is the same for all its components. This leads to zig zag weight updates. See lecture 6.


In [39]:
import numpy as np
import matplotlib.pyplot as plt

def sigmoid(x):
    return 1/(1+np.exp(-x))

x = np.linspace(-10, 10)
plt.plot(sigmoid(x))
plt.show()


d = 2
n =1
h = 3
ws = 1e-2
result = list()
dws = list()
for i in range(10000):
    x = np.random.randn(n,d)
    w1 = ws * np.random.randn(d,h)
    b1 = 0
    z1 = x.dot(w1) + b1
    a1 = sigmoid(z1)
    dw = x.T.dot(sigmoid(a1) * (1-sigmoid(a1)))
    if len(dw[dw > 0] == len(dw)):
        result.append(True)
        dws.append(dw)
    elif len(dw[dw < 0] == len(dw)):
        result.append(False)
        dws.append(dw)

print(x, w1, z1, a1, dw, sep="\n\n")
print(sum(result))

[[-0.57230354  1.75349343]]

[[ 0.03240976 -0.00220158  0.00569603]
 [-0.00745333 -0.00614806  0.00798578]]

[[-0.03161758 -0.00952061  0.01074316]]

[[0.49209626 0.49761987 0.50268577]]

[[-0.13475208 -0.1345717  -0.13440479]
 [ 0.41286986  0.4123172   0.41180579]]
7511


## Weight initialisation

In [16]:
import numpy as np
import seaborn as sns

a = np.tanh(np.random.randn(1000,1) * 10)
print(np.mean(a), np.std(a))

-0.0023178973172205382 0.9692424334644353


In [27]:
from numpy.random import uniform
for i in range(10):
    print(10**uniform(-3,-6))

0.00038303892339165214
5.453555697064419e-05
3.419691108677078e-06
0.00014452196415636333
4.550046702347725e-06
1.3286976401643098e-06
2.5425871027502573e-06
3.323537663510148e-06
4.181725250328e-06
0.00011574019499552648


# Adam

In [3]:
import numpy as np

np.sqrt(-1)

/home/sebastian/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:3: RuntimeWarning: invalid value encountered in sqrt
  This is separate from the ipykernel package so we can avoid doing imports until


nan